#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

nameservers=''
for ns in "$DNS" `env | grep -E '^ETH[0-9]+_DNS=' | sort | cut -d= -f2`; do
  if [ -n "$ns" ]; then
    nameservers="$nameservers $ns"
  fi
done

searchdomains=''
for dom in "$SEARCH_DOMAIN" `env | grep -E '^ETH[0-9]+_SEARCH_DOMAIN=' | sort | cut -d= -f2`; do
  if [ -n "$dom" ]; then
    searchdomains="$searchdomains $dom"
  fi
done

[ -z "$nameservers" ] && exit 0

sed -i '' -e "/^nameserver /d" /etc/resolv.conf

for ns in $nameservers; do
  echo "nameserver $ns"
done >> /etc/resolv.conf

[ -z "$searchdomains" ] && exit 0

sed -i '' -e "/^search /d" /etc/resolv.conf

echo "search $searchdomains" >> /etc/resolv.conf

exit 0
