#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ -z "$SSH_PUBLIC_KEY" -a -z "$EC2_PUBLIC_KEY" ]; then
  exit 0
fi

mkdir -m0700 /root/.ssh
if [ ! -f /root/.ssh/authorized_keys ]; then
  cat /dev/null > /root/.ssh/authorized_keys
fi
if [ -z "$SSH_KEEP_KEYS" ]; then
  cat /dev/null > /root/.ssh/authorized_keys
fi

if [ -n "$SSH_PUBLIC_KEY" ]; then
  grep -q "$SSH_PUBLIC_KEY" /root/.ssh/authorized_keys
  if [ $? -ne 0 ]; then
    echo "$SSH_PUBLIC_KEY" >> /root/.ssh/authorized_keys
    sed -i '' -e 's/\\n/\n/g' /root/.ssh/authorized_keys
  fi
fi

if [ -n "$EC2_PUBLIC_KEYS" ]; then
  grep -q "$EC2_PUBLIC_KEY" /root/.ssh/authorized_keys
  if [ $? -ne 0 ]; then
    echo "$EC2_PUBLIC_KEY" >> /root/.ssh/authorized_keys
    sed -i '' -e 's/\\n/\n/g' /root/.ssh/authorized_keys
  fi
fi

chmod 600 /root/.ssh/authorized_keys

exit 0
